### ISSUE TITLE
[question] Any chance of generating the same key?

### ISSUE THREAD

**Issue by ianwieds** [nwoltman/node-uid-generator#3]
Really great library! Thank you!

Was wondering if we use this to generate API keys if there is any reason a key could be generated twice? I assume not but just double-checking. I didn't see anything related to date/time in the code, just pure random so perhaps if we get unlucky could a key be generated twice for two different users?

Thanks again

**Comment by nwoltman** [comment]
Hi @iwiedenm! I'm glad you're liking the library!

You are correct. Since the UID is randomly generated using only the system's entropy, there is a possibility that the same key could be generated twice. However, this possibility is so small that it's basically zero. [This section on Wikipedia](https://en.wikipedia.org/w/index.php?title=Universally_unique_identifier&oldid=755882275#Random_UUID_probability_of_duplicates) has some good information on the subject.

Since this library generates UIDs in the same way as version 4 UUIDs, the same formula from that article can be used. By default, this library generates 128-bit UIDs, so here's the calculation for that: 

```
p(n) = n^2 / (2 * 2^128)
p(1 trillion) = 0.00000000000000147
```

So even after generating 1 trillion UIDs, there's only a 0.00000000000000147 chance of two of them being the same.

To get up to a 50% chance of a collision, you'd need to generate over 18 quintillion UIDs, which would take over 570 years if you were generating 1 billion UIDs every second.

**Comment by ianwieds** [comment]
Thank you @nwoltman for the detailed answer. I see now it's not an issue so I'll stop worrying about it :) Thanks again for a great & well-made library. Cheers!

**Comment by jeroentrappers** [comment]
We have had a collision in production using version 1.0.0 of this library. So the chance is certainly not zero ;-)

**Comment by nwoltman** [comment]
@jeroentrappers That's actually amazing. If you were using the default bit size of 128, you just hit a 0.5 in 18 quintillion chance. Probably a good reminder that even though something is very unlikely, it's still possible.
